name: CI (Build & Test)

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Si NO hay package.json, que pase igual
      - name: Skip (no Node project)
        if: ${{ hashFiles('package.json') == '' }}
        run: echo "No package.json found. Skipping build/test."

      - name: Setup Node.js
        if: ${{ hashFiles('package.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        if: ${{ hashFiles('package.json') != '' }}
        run: npm ci

      - name: Lint (if present)
        if: ${{ hashFiles('package.json') != '' }}
        run: npm run lint --if-present

      - name: Prettier check (if present)
        if: ${{ hashFiles('package.json') != '' }}
        run: npm run prettier:check --if-present

      - name: Run tests (if present)
        if: ${{ hashFiles('package.json') != '' }}
        run: npm test --if-present

      - name: Build project (if present)
        if: ${{ hashFiles('package.json') != '' }}
        run: npm run build --if-present
